# Generated by Django 3.2.12 on 2022-05-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='change_variable',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
