# Generated by Django 3.2.12 on 2022-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_apps', '0003_alter_message_change_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='change_variable',
            field=models.IntegerField(),
        ),
    ]
