# Generated by Django 4.0.5 on 2022-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_apps', '0004_alter_message_change_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='change_variable1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='change_variable2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='change_variable3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
