# Generated by Django 4.0.5 on 2022-06-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_apps', '0005_message_change_variable1_message_change_variable2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='change_variable2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='change_variable3',
        ),
    ]
